# Generated by Django 6.0.6 on 2026-08-12 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='category',
            field=models.CharField(choices=[('personal', 'Personal'), ('study', 'Study'), ('memories', 'Memories'), ('goals', 'Goals'), ('other', 'Other')], default='personal', max_length=20),
        ),
    ]
