# Generated by Django 6.0.6 on 2026-08-12 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_journalentry_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
