# Generated by Django 6.1 on 2026-08-13 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_journalentry_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='mood',
            field=models.CharField(choices=[('happy', '😊 Happy'), ('calm', '😌 Calm'), ('loved', '🥰 Loved'), ('sad', '😢 Sad'), ('angry', '😡 Angry'), ('anxious', '😰 Anxious'), ('tired', '😴 Tired')], default='happy', max_length=20),
        ),
    ]
