# Generated by Django 6.0.6 on 2026-08-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_journalentry_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
