# Generated by Django 6.0.6 on 2026-08-17 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_journalentry_is_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='journal_media/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='journal.journalentry')),
            ],
        ),
    ]
